## @file
# Azure Pipeline build file for building a platform.
#
# Platform: OVMF
# OS: Windows
# Toolchain: VS2019
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
##
trigger:
  - master
pr:
  - master

jobs:
  - job: Build_VS2019_OVMF

    #Use matrix to speed up the build process
    strategy:
      matrix:
        OVMF_IA32_DEBUG:
          Build.File: "OvmfPkg/PlatformBuild.py"
          Build.Arch: "IA32"
          Build.Flags: ""
          Build.Target: "DEBUG"
    workspace:
      clean: all

    pool:
      vmImage: "windows-latest"

    steps:
      - checkout: none
        clean: true
        fetchDepth: 1


      - powershell: choco install qemu # contents of the script to run
        displayName: Install QEMU # friendly name displayed in the UI

      - script: dir "c:\program files\qemu"
        displayName: find the qemu folder
