## @file
# Azure Pipeline build file for building a platform.
#
# Platform: OVMF
# OS: Windows
# Toolchain: VS2019
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
##
trigger:
  - master
pr:
  - master

jobs:
  - job: Build_VS2019_OVMF

    #Use matrix to speed up the build process
    strategy:
      matrix:
        OVMF_IA32_DEBUG:
          Build.File: "OvmfPkg/PlatformBuild.py"
          Build.Arch: "IA32"
          Build.Flags: ""
          Build.Target: "DEBUG"
        OVMF_IA32_RELEASE:
          Build.File: "OvmfPkg/PlatformBuild.py"
          Build.Arch: "IA32"
          Build.Flags: ""
          Build.Target: "RELEASE"
        OVMF_X64_DEBUG:
          Build.File: "OvmfPkg/PlatformBuild.py"
          Build.Arch: "X64"
          Build.Flags: ""
          Build.Target: "DEBUG"
        OVMF_X64_RELEASE:
          Build.File: "OvmfPkg/PlatformBuild.py"
          Build.Arch: "X64"
          Build.Flags: ""
          Build.Target: "RELEASE"
        OVMF_IA32X64_DEBUG:
          Build.File: "OvmfPkg/PlatformBuild.py"
          Build.Arch: "IA32,X64"
          Build.Flags: ""
          Build.Target: "DEBUG"
        OVMF_IA32X64_RELEASE:
          Build.File: "OvmfPkg/PlatformBuild.py"
          Build.Arch: "IA32,X64"
          Build.Flags: ""
          Build.Target: "RELEASE"
        OVMF_IA32X64_FULL_DEBUG:
          Build.File: "OvmfPkg/PlatformBuild.py"
          Build.Arch: "IA32,X64"
          Build.Flags: "BLD_*_SECURE_BOOT_ENABLE=1 BLD_*_SMM_REQUIRE=1 BLD_*_TPM_ENABLE=1 BLD_*_TPM_CONFIG_ENABLE=1 BLD_*_NETWORK_TLS_ENABLE=1 BLD_*_NETWORK_IP6_ENABLE=1 BLD_*_NETWORK_HTTP_BOOT_ENABLE=1"
          Build.Target: "DEBUG"
        OVMF_IA32X64_FULL_RELEASE:
          Build.File: "OvmfPkg/PlatformBuild.py"
          Build.Arch: "IA32,X64"
          Build.Flags: "BLD_*_SECURE_BOOT_ENABLE=1 BLD_*_SMM_REQUIRE=1 BLD_*_TPM_ENABLE=1 BLD_*_TPM_CONFIG_ENABLE=1 BLD_*_NETWORK_TLS_ENABLE=1 BLD_*_NETWORK_IP6_ENABLE=1 BLD_*_NETWORK_HTTP_BOOT_ENABLE=1"
          Build.Target: "RELEASE"
    workspace:
      clean: all

    pool:
      vmImage: "windows-latest"

    variables:
      python_version: "3.8.x"
      tool_chain_tag: "VS2019"

    steps:
      - checkout: self
        clean: true
        fetchDepth: 1

      - task: UsePythonVersion@0
        inputs:
          versionSpec: $(python_version)
          architecture: "x64"

      - script: pip install -r pip-requirements.txt --upgrade
        displayName: "Install/Upgrade pip modules"

      # Build base tools
      - task: CmdLine@1
        displayName: Build Base Tools from source
        inputs:
          filename: python
          arguments: BaseTools/Edk2ToolsBuild.py -t $(tool_chain_tag)

      - task: CopyFiles@2
        displayName: "Copy base tools build log"
        inputs:
          targetFolder: "$(Build.ArtifactStagingDirectory)"
          SourceFolder: "BaseTools/BaseToolsBuild"
          contents: |
            BASETOOLS_BUILD*.*
          flattenFolders: true

      # Setup repo
      - task: CmdLine@1
        displayName: Setup
        inputs:
          filename: stuart_setup
          arguments: -c $(Build.File) TOOL_CHAIN_TAG=$(tool_chain_tag) -t $(Build.Target) -a $(Build.Arch) $(Build.Flags)
      # Stuart Update
      - task: CmdLine@1
        displayName: Update
        inputs:
          filename: stuart_update
          arguments: -c $(Build.File) TOOL_CHAIN_TAG=$(tool_chain_tag) -t $(Build.Target) -a $(Build.Arch) $(Build.Flags)
      # Build
      - task: CmdLine@1
        displayName: Build
        inputs:
          filename: stuart_build
          arguments: -c $(Build.File) TOOL_CHAIN_TAG=$(tool_chain_tag) TARGET=$(Build.Target) -a $(Build.Arch) $(Build.Flags)
      # execute emulator
      - task: CmdLine@1
        displayName: Build
        inputs:
          filename: stuart_build
          arguments: -c $(Build.File) TOOL_CHAIN_TAG=$(tool_chain_tag) TARGET=$(Build.Target) -a $(Build.Arch) $(Build.Flags) MAKE_STARTUP_NSH=TRUE --FlashOnly
        timeoutInMinutes: 1

      # Copy the build logs to the artifact staging directory
      - task: CopyFiles@2
        displayName: "Copy build logs"
        inputs:
          targetFolder: "$(Build.ArtifactStagingDirectory)"
          SourceFolder: "Build"
          contents: |
            BUILDLOG_*.txt
            BUILDLOG_*.md
            CI_*.txt
            CI_*.md
            CISETUP.txt
            SETUPLOG.txt
            UPDATE_LOG.txt
            PREVALLOG.txt
            TestSuites.xml
            **/BUILD_TOOLS_REPORT.html
            **/OVERRIDELOG.TXT
            BASETOOLS_BUILD*.*
            BootLog.txt
          flattenFolders: true
        condition: succeededOrFailed()

      # Publish build artifacts to Azure Artifacts/TFS or a file share
      - task: PublishBuildArtifacts@1
        continueOnError: true
        displayName: "Publish build logs"
        inputs:
          pathtoPublish: "$(Build.ArtifactStagingDirectory)"
          artifactName: "Build Logs $(System.JobName)"
        condition: succeededOrFailed()

  - job: FINISHED
    dependsOn: Build_VS2019_OVMF
    condition: succeeded()
    steps:
      - checkout: none
      - script: |
          echo FINISHED
          sleep 10
        displayName: FINISHED

  - job: FAILED
    dependsOn: Build_VS2019_OVMF
    condition: failed()
    steps:
      - checkout: none
      - script: |
          echo FAILED
          sleep 10
        displayName: FAILED
