##
# Azure Pipeline build file for a CI build using ubuntu and GCC5
#
# Copyright (c) 2019, Microsoft Corporation
# SPDX-License-Identifier: BSD-2-Clause-Patent
##
trigger: 
- master

pr: none

variables:
  GCC_AARCH_PREFIX: bin/aarch64-linux-gnu-

jobs:
- template: templates/pr-gate-build-job.yml
  parameters:
    tool_chain_tag: 'GCC5'
    vm_image: 'ubuntu-latest'
