trigger: 
- master

pr: none

variables:
  GCC_AARCH_PREFIX: bin/aarch64-linux-gnu-

jobs:
- template: templates/pr-gate-build-job.yml
  parameters:
    tool_chain_tag: 'GCC5'
    vm_image: 'ubuntu-latest'
    
