##
# Azure Pipeline build file for a PR build using Windows and VS2019
#
# Copyright (c) 2019, Microsoft Corporation
# SPDX-License-Identifier: BSD-2-Clause-Patent
##
trigger: none
pr: 
- prtest/master

jobs:
- template: templates/pr-gate-build-job.yml
  parameters:
    tool_chain_tag: 'VS2019'
    vm_image: 'windows-latest'
    
